"""Deterministic semantic/procedural ecologies for transfer qualification.

This module is deliberately a small scientific instrument: symbolic state is
generated by Python, rendered through fixed templates, and verified without an
LLM.  Hidden theta is never included in a model prompt.
"""

from __future__ import annotations

import hashlib
import itertools
import json
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

OUTPUT_CLASSES = ("APPROVE", "DENY", "ESCALATE", "DEFER")
ROOT_CLASSES = ("ROLLBACK", "RETRY", "ISOLATE", "ESCALATE")


def stable_hash(value: Any) -> str:
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


@dataclass(frozen=True)
class Case:
    family: str
    case_id: str
    template: str
    entities: tuple[str, ...]
    fields: dict[str, Any]
    expected: str

    def symbolic(self) -> dict[str, Any]:
        return {"family": self.family, "case_id": self.case_id, "template": self.template,
                "entities": list(self.entities), "fields": self.fields, "expected": self.expected}


@dataclass(frozen=True)
class Environment:
    ecology: str
    seed: int
    theta: dict[str, dict[str, Any]]
    metadata: dict[str, Any]


class Ecology:
    name: str
    output_classes: tuple[str, ...] = OUTPUT_CLASSES
    families: tuple[str, ...] = ("ACCESS", "RELEASE", "INCIDENT", "PROVENANCE")

    def generate_environment(self, seed: int) -> Environment:
        raise NotImplementedError

    def candidate_thetas(self, family: str, environment: Environment) -> list[dict[str, Any]]:
        raise NotImplementedError

    def solve(self, environment: Environment, family: str, fields: dict[str, Any]) -> str:
        raise NotImplementedError

    def render_case(self, family: str, case: Case) -> str:
        raise NotImplementedError

    def case_pool(self, environment: Environment, family: str, *, template: str) -> list[Case]:
        raise NotImplementedError

    def training_cases(self, environment: Environment, family: str, h: int) -> list[Case]:
        pool = self.case_pool(environment, family, template="train")
        probes = {c.case_id for c in self.probe_cases(environment, family)}
        pool = [c for c in pool if c.case_id not in probes]
        candidates = self.candidate_thetas(family, environment)
        remaining = list(range(len(candidates)))
        chosen: list[Case] = []
        for case in pool:
            partitions = {self.solve_with_theta(candidates[i], family, case.fields) for i in remaining}
            if len(partitions) > 1:
                chosen.append(case)
                truth = case.expected
                remaining = [i for i in remaining if self.solve_with_theta(candidates[i], family, case.fields) == truth]
            if len(chosen) >= h or len(remaining) <= 1:
                break
        # Fill deterministically if the teaching set is smaller than h.
        for case in pool:
            if len(chosen) >= h:
                break
            if case.case_id not in {x.case_id for x in chosen}:
                chosen.append(case)
        return chosen[:h]

    def probe_cases(self, environment: Environment, family: str) -> list[Case]:
        pool = self.case_pool(environment, family, template="eval")
        selected: list[Case] = []
        counts = {label: 0 for label in self.output_classes}
        for case in pool:
            if counts[case.expected] < 2:
                selected.append(case)
                counts[case.expected] += 1
            if all(value == 2 for value in counts.values()):
                return selected
        raise ValueError(f"unable to balance probes for {self.name}/{family}: {counts}")

    def solve_with_theta(self, theta: dict[str, Any], family: str, fields: dict[str, Any]) -> str:
        raise NotImplementedError

    def render_experience(self, case: Case) -> str:
        return f"Previous resolved case:\n{self.render_case(case.family, case)}\nCorrect resolution: {case.expected}"

    def render_query(self, case: Case, memories: Iterable[str]) -> str:
        memory = "\n\n".join(memories)
        prefix = f"Prior resolved cases:\n{memory}\n\n" if memory else ""
        labels = "|".join(self.output_classes)
        return prefix + self.render_case(case.family, case) + f"\nReturn only JSON: {{\"answer\": \"{labels}\", \"confidence\": <number 0..1>}}"


class OPEcology(Ecology):
    """Organizational Procedure Ecology with known two-block overlap."""

    name = "OPE"

    def generate_environment(self, seed: int) -> Environment:
        rng = random.Random(0x0A11CE + seed * 7919)
        block0 = {"threshold": rng.choice((2, 3)), "compatibility": rng.choice(("strict", "broad"))}
        block1 = {"threshold": rng.choice((2, 3)), "provenance": rng.choice(("required", "optional"))}
        theta = {
            "ACCESS": {**block0, "exception": rng.choice(("ESCALATE", "DENY")), "block": 0},
            "RELEASE": {**block0, "exception": rng.choice(("ESCALATE", "DENY")), "block": 0},
            "INCIDENT": {**block1, "temporal": rng.choice(("strict", "relaxed")), "block": 1},
            "PROVENANCE": {**block1, "temporal": rng.choice(("strict", "relaxed")), "block": 1},
        }
        return Environment(self.name, seed, theta, {"blocks": {"ACCESS": 0, "RELEASE": 0, "INCIDENT": 1, "PROVENANCE": 1}})

    def candidate_thetas(self, family: str, environment: Environment) -> list[dict[str, Any]]:
        if family in ("ACCESS", "RELEASE"):
            return [{"threshold": t, "compatibility": c, "exception": e, "block": 0}
                    for t in (2, 3) for c in ("strict", "broad") for e in ("ESCALATE", "DENY")]
        return [{"threshold": t, "provenance": p, "temporal": v, "block": 1}
                for t in (2, 3) for p in ("required", "optional") for v in ("strict", "relaxed")]

    def solve_with_theta(self, theta: dict[str, Any], family: str, fields: dict[str, Any]) -> str:
        if fields["exception"]:
            return theta["exception"] if theta.get("block") == 0 else "ESCALATE"
        if fields["criticality"] >= theta["threshold"]:
            return "ESCALATE"
        if theta.get("block") == 0:
            compatible = fields["role"] == fields["resource"] if theta["compatibility"] == "strict" else fields["role"] in {"operator", "owner"}
            if not compatible:
                return "DENY"
        else:
            if not fields["provenance"] and (theta["provenance"] == "required" or fields["criticality"] == 1):
                return "DENY"
            if theta["temporal"] == "strict" and not fields["temporal_valid"]:
                return "DEFER"
        if fields["approval"] != "approved":
            return "DEFER"
        return "APPROVE"

    def solve(self, environment: Environment, family: str, fields: dict[str, Any]) -> str:
        return self.solve_with_theta(environment.theta[family], family, fields)

    def case_pool(self, environment: Environment, family: str, *, template: str) -> list[Case]:
        rng = random.Random(environment.seed * 104729 + sum(ord(x) for x in family) + (1 if template == "eval" else 0))
        records: list[Case] = []
        roles = ("operator", "owner", "reviewer", "visitor")
        resources = ("operator", "owner", "archive", "service")
        for index, (criticality, role, resource, approval, provenance, temporal, exception) in enumerate(
            itertools.product((1, 2, 3), roles, resources, ("approved", "pending"), (False, True), (False, True), (False, True))):
            fields = {"criticality": criticality, "role": role, "resource": resource, "approval": approval,
                      "provenance": provenance, "temporal_valid": temporal, "exception": exception}
            expected = self.solve(environment, family, fields)
            entities = (f"{family.lower()}-{environment.seed}-{template}-{index}",)
            case = Case(family, f"{family}-{environment.seed}-{template}-{index}", template, entities, fields, expected)
            records.append(case)
        rng.shuffle(records)
        return records

    def render_case(self, family: str, case: Case) -> str:
        f = case.fields
        domain = {"ACCESS": "A staff member requests access to a controlled service.",
                  "RELEASE": "A change owner requests release of a service update.",
                  "INCIDENT": "An operations team is reviewing an incident timeline.",
                  "PROVENANCE": "An evidence custodian is reviewing a record release."}[family]
        return (f"{domain}\nRequester role: {f['role']}. Resource or service: {f['resource']}. "
                f"Criticality: {f['criticality']}/3. Approval state: {f['approval']}. "
                f"Evidence lineage present: {'yes' if f['provenance'] else 'no'}. "
                f"Required time window valid: {'yes' if f['temporal_valid'] else 'no'}. "
                f"An unusual condition is {'present' if f['exception'] else 'absent'}. "
                "Determine the appropriate organizational resolution.")


class OPEGeometryV2Ecology(OPEcology):
    """OPE extension with preregistered latent-factor sharing geometries.

    The semantic surface and exact OPE verifier are retained.  Only the
    run-specific parameter tying changes across GLOBAL/BLOCK/DIAGONAL.  The
    factor incidence and parameter table are kept in experimenter metadata and
    are never rendered to the model.
    """

    GEOMETRIES = ("GLOBAL", "BLOCK", "DIAGONAL")

    def __init__(self, geometry: str) -> None:
        if geometry not in self.GEOMETRIES:
            raise ValueError(f"unknown OPE geometry: {geometry}")
        self.geometry = geometry
        self.name = f"OPE-GEOMETRY-V2-{geometry}"

    def _factor_ids(self, family: str) -> tuple[str, str, str]:
        if self.geometry == "GLOBAL":
            return ("global.threshold", "global.compatibility", f"unique.{family}.exception")
        if self.geometry == "BLOCK":
            block = 0 if family in ("ACCESS", "RELEASE") else 1
            return (f"block{block}.threshold", f"block{block}.compatibility", f"unique.{family}.exception")
        return (f"unique.{family}.threshold", f"unique.{family}.compatibility", f"unique.{family}.exception")

    @staticmethod
    def _factor_value(factor_id: str, seed: int) -> Any:
        # Three bits give a compact, deterministic parameter code.  Adjacent
        # paired seeds therefore cannot accidentally produce an identical
        # three-factor theta, while each factor remains independently valued.
        code = (seed + sum(ord(x) for x in factor_id) * 17) % 8
        if factor_id.endswith("threshold"):
            return 2 + (code & 1)
        if factor_id.endswith("compatibility"):
            return ("strict", "broad")[(code >> 1) & 1]
        return ("ESCALATE", "DENY")[(code >> 2) & 1]

    def generate_environment(self, seed: int) -> Environment:
        factor_ids = {family: self._factor_ids(family) for family in self.families}
        all_ids = sorted({factor for factors in factor_ids.values() for factor in factors})
        factor_values = {factor: self._factor_value(factor, seed) for factor in all_ids}
        theta: dict[str, dict[str, Any]] = {}
        for family, factors in factor_ids.items():
            theta[family] = {
                "threshold": factor_values[factors[0]],
                "compatibility": factor_values[factors[1]],
                "exception": factor_values[factors[2]],
                "factor_ids": factors,
            }
        incidence = [[int(factor in factors) for factor in all_ids] for factors in factor_ids.values()]
        overlap = []
        for row in incidence:
            overlap.append([sum(a * b for a, b in zip(row, other)) / 3.0 for other in incidence])
        metadata = {
            "geometry": self.geometry,
            "factor_ids_by_family": factor_ids,
            "factor_values": factor_values,
            "factor_incidence": incidence,
            "factor_order": all_ids,
            "designed_overlap": overlap,
            "blocks": {"ACCESS": 0, "RELEASE": 0, "INCIDENT": 1, "PROVENANCE": 1},
        }
        return Environment(self.name, seed, theta, metadata)

    def candidate_thetas(self, family: str, environment: Environment) -> list[dict[str, Any]]:
        # All three substantive factors are independently variable in the
        # local hypothesis space.  The environment only determines truth.
        return [{"threshold": threshold, "compatibility": compatibility,
                 "exception": exception, "block": environment.metadata["blocks"][family]}
                for threshold in (2, 3) for compatibility in ("strict", "broad")
                for exception in ("ESCALATE", "DENY")]

    def solve_with_theta(self, theta: dict[str, Any], family: str, fields: dict[str, Any]) -> str:
        if fields["exception"]:
            return theta["exception"]
        if fields["criticality"] >= theta["threshold"]:
            return "ESCALATE"
        compatible = (fields["role"] == fields["resource"] if theta["compatibility"] == "strict"
                      else fields["role"] in {"operator", "owner"})
        if not compatible:
            return "DENY"
        if fields["approval"] != "approved":
            return "DEFER"
        return "APPROVE"

    def solve(self, environment: Environment, family: str, fields: dict[str, Any]) -> str:
        return self.solve_with_theta(environment.theta[family], family, fields)


class CWDEcology(Ecology):
    """Causal Workflow Diagnosis Ecology with mostly niche-specific codebooks."""

    name = "CWDE"
    output_classes = ROOT_CLASSES

    def generate_environment(self, seed: int) -> Environment:
        rng = random.Random(0xC0DE + seed * 6151)
        # A/B share a propagation motif; C/D share a different motif.  The
        # action permutation and exception policy are niche-specific.
        theta = {}
        for index, family in enumerate(self.families):
            motif = "chain" if index < 2 else "fanout"
            permutation = list(ROOT_CLASSES); rng.shuffle(permutation)
            theta[family] = {"motif": motif, "permutation": tuple(permutation), "exception": rng.choice(("RETRY", "ESCALATE")), "block": int(index >= 2)}
        return Environment(self.name, seed, theta, {"blocks": {"ACCESS": 0, "RELEASE": 0, "INCIDENT": 1, "PROVENANCE": 1}})

    def candidate_thetas(self, family: str, environment: Environment) -> list[dict[str, Any]]:
        motif = "chain" if family in ("ACCESS", "RELEASE") else "fanout"
        return [{"motif": motif, "permutation": permutation, "exception": exception, "block": int(motif == "fanout")}
                for permutation in itertools.permutations(ROOT_CLASSES) for exception in ("RETRY", "ESCALATE")]

    def _root(self, theta: dict[str, Any], fields: dict[str, Any]) -> int:
        if fields["exception"]:
            return 3
        if theta["motif"] == "chain":
            return (fields["failed_dependency"] + fields["retry_count"] + (0 if fields["ack"] else 1)) % 4
        return (fields["failed_dependency"] * 2 + fields["validation_gap"] + (1 if fields["ack"] else 0)) % 4

    def solve_with_theta(self, theta: dict[str, Any], family: str, fields: dict[str, Any]) -> str:
        root = self._root(theta, fields)
        if fields["exception"]:
            return theta["exception"]
        return theta["permutation"][root]

    def solve(self, environment: Environment, family: str, fields: dict[str, Any]) -> str:
        return self.solve_with_theta(environment.theta[family], family, fields)

    def case_pool(self, environment: Environment, family: str, *, template: str) -> list[Case]:
        rng = random.Random(environment.seed * 130363 + sum(ord(x) for x in family) + (3 if template == "eval" else 0))
        records: list[Case] = []
        for index, values in enumerate(itertools.product(range(4), range(3), (False, True), range(3), (False, True))):
            failed_dependency, retry_count, ack, validation_gap, exception = values
            fields = {"failed_dependency": failed_dependency, "retry_count": retry_count, "ack": ack,
                      "validation_gap": validation_gap, "exception": exception}
            expected = self.solve(environment, family, fields)
            service = ("Mira", "Kestrel", "Orchid", "Tern")[environment.seed % 4]
            entity = f"{service}-{family.lower()}-{environment.seed}-{template}-{index}"
            records.append(Case(family, f"{family}-{environment.seed}-{template}-{index}", template, (entity,), fields, expected))
        rng.shuffle(records)
        return records[:300]

    def render_case(self, family: str, case: Case) -> str:
        f = case.fields
        motif = "a dependency chain" if family in ("ACCESS", "RELEASE") else "a parallel service fan-out"
        return (f"A fictional service incident is being triaged through {motif}. "
                f"The log reports dependency marker {f['failed_dependency']}, {f['retry_count']} retries, "
                f"an acknowledgement is {'present' if f['ack'] else 'missing'}, and {f['validation_gap']} validation gaps. "
                f"An unusual operational condition is {'present' if f['exception'] else 'absent'}. "
                "Infer the root remediation class from this run-specific incident log.")


ECOLOGIES: dict[str, Ecology] = {"OPE": OPEcology(), "CWDE": CWDEcology()}
GEOMETRY_ECOLOGIES: dict[str, OPEGeometryV2Ecology] = {
    geometry: OPEGeometryV2Ecology(geometry) for geometry in OPEGeometryV2Ecology.GEOMETRIES
}


def parse_action(raw: str | None) -> tuple[str | None, float | None, str | None]:
    if not raw:
        return None, None, "empty"
    try:
        value = json.loads(raw)
    except json.JSONDecodeError:
        return None, None, "malformed"
    if not isinstance(value, dict) or not isinstance(value.get("answer"), str):
        return None, None, "schema"
    answer = value["answer"].strip().upper()
    confidence = value.get("confidence")
    try:
        confidence = float(confidence)
    except (TypeError, ValueError):
        return None, None, "schema"
    if answer not in OUTPUT_CLASSES and answer not in ROOT_CLASSES:
        return None, confidence, "out_of_domain"
    if not 0.0 <= confidence <= 1.0:
        return None, None, "schema"
    return answer, confidence, None


def predictive_identifiability(ecology: Ecology, environment: Environment, family: str, h: int) -> dict[str, Any]:
    train = ecology.training_cases(environment, family, h)
    candidates = ecology.candidate_thetas(family, environment)
    consistent = [theta for theta in candidates if all(ecology.solve_with_theta(theta, family, case.fields) == case.expected for case in train)]
    probes = ecology.probe_cases(environment, family)
    identifiable = [all(ecology.solve_with_theta(theta, family, probe.fields) == ecology.solve_with_theta(consistent[0], family, probe.fields) for theta in consistent) for probe in probes] if consistent else [False] * len(probes)
    return {"h": h, "training_count": len(train), "candidate_count": len(candidates), "consistent_count": len(consistent),
            "probe_count": len(probes), "predictively_identifiable": sum(identifiable) / len(identifiable),
            "oracle_accuracy": sum(ecology.solve(environment, family, p.fields) == p.expected for p in probes) / len(probes)}
